### ISSUE TITLE
'gulp build' has an error for me

### ISSUE THREAD

**Issue by jefffranks** [iroy2000/react-reflux-boilerplate-with-webpack#2]
Hi,

I just did a git clone and followed the README.md instructions.
'gulp build' failed in three places and is telling me I need a loader for a specific file type.

I don't know how to fix this. Please let me know what I have to do.

Bellow is a truncated session log that shows the errors:
---- console session ----
jfranks@jlf-mint-17 ~/Desktop/ws3 - react reflux boilerplate with webpack/react-reflux-boilerplate-with-webpack $ gulp build
....
....
....
Dropping unreachable code [./~/style-loader!./~/css-loader!./public/main.css:11,0]
Side effects in initialization of unused variable update [./~/style-loader!./~/css-loader!./public/main.css:7,0]
Condition always false [./~/style-loader/addStyles.js:23,0]
Dropping unreachable code [./~/style-loader/addStyles.js:24,0]
Side effects in initialization of unused variable support [./~/lodash/index.js:4351,10]
Dropping unused variable object [./~/lodash/index.js:948,10]
Condition always true [./~/lodash/index.js:12207,6]
Dropping unreachable code [./~/lodash/index.js:12221,7]
Side effects in initialization of unused variable moduleExports [./~/lodash/index.js:275,6]

ERROR in ./assets/images/wac.jpg
Module parse failed: /home/jfranks/Desktop/ws3 - react reflux boilerplate with webpack/react-reflux-boilerplate-with-webpack/node_modules/image-webpack-loader/index.js?bypassOnDebug&optimizationLevel=7&interlaced=false&progressive=true!/home/jfranks/Desktop/ws3 - react reflux boilerplate with webpack/react-reflux-boilerplate-with-webpack/assets/images/wac.jpg Line 1: Unexpected token ILLEGAL
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)
 @ ./~/css-loader!./public/main.css 2:15613-15648

ERROR in ./assets/images/bg_pattern.png
Module parse failed: /home/jfranks/Desktop/ws3 - react reflux boilerplate with webpack/react-reflux-boilerplate-with-webpack/node_modules/image-webpack-loader/index.js?bypassOnDebug&optimizationLevel=7&interlaced=true!/home/jfranks/Desktop/ws3 - react reflux boilerplate with webpack/react-reflux-boilerplate-with-webpack/assets/images/bg_pattern.png Line 1: Unexpected token ILLEGAL
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)
 @ ./~/css-loader!./public/main.css 2:14317-14359

ERROR in ./assets/images/overlay.png
Module parse failed: /home/jfranks/Desktop/ws3 - react reflux boilerplate with webpack/react-reflux-boilerplate-with-webpack/node_modules/image-webpack-loader/index.js?bypassOnDebug&optimizationLevel=7&interlaced=true!/home/jfranks/Desktop/ws3 - react reflux boilerplate with webpack/react-reflux-boilerplate-with-webpack/assets/images/overlay.png Line 1: Unexpected token ILLEGAL
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)
 @ ./~/css-loader!./public/main.css 2:13734-13773
[15:47:09] Finished 'webpack:build' after 37 s
[15:47:09] Starting 'build'...
[15:47:09] Finished 'build' after 21 μs

**Comment by iroy2000** [comment]
Let me check out the project and take a look, will get back to you.
