### ISSUE TITLE
'gulp test' fails for me

### ISSUE THREAD

**Issue by jefffranks** [iroy2000/react-reflux-boilerplate-with-webpack#3]
Hi,
I did the git pull and updated to the latest just now.
'gulp test' fails for me. <Note: I've setup .profile and .bashrc with the alias specified>

---- console session error ----
jfranks@jlf-mint-17 ~/Desktop/ws3 - react reflux boilerplate with webpack/react-reflux-boilerplate-with-webpack $ gulp test
[21:27:57] Requiring external module coffee-script/register
[21:27:59] Using gulpfile ~/Desktop/ws3 - react reflux boilerplate with webpack/react-reflux-boilerplate-with-webpack/gulpfile.coffee
[21:27:59] Starting 'test'...
 FAIL  __tests__/app.cjsx
Error: /home/jfranks/Desktop/ws3 - react reflux boilerplate with webpack/react-reflux-boilerplate-with-webpack/__tests__/app.cjsx: Cannot find module '../src/scripts/components/about' from '/home/jfranks/Desktop/ws3 - react reflux boilerplate with webpack/react-reflux-boilerplate-with-webpack/__tests__/app.cjsx'
1 test failed, 0 tests passed (1 total)
Run time: 0.616s
[21:28:02] Finished 'test' after 3.32 s

$ ls -l
total 52
drwxr-xr-x  3 jfranks jfranks 4096 May 29 15:03 assets
-rw-r--r--  1 jfranks jfranks 4658 May 29 15:03 gulpfile.coffee
drwxr-xr-x 42 jfranks jfranks 4096 May 29 15:37 node_modules
-rw-r--r--  1 jfranks jfranks 1791 May 29 15:03 package.json
-rw-r--r--  1 jfranks jfranks  301 May 29 15:03 preprocessor.js
drwxr-xr-x  4 jfranks jfranks 4096 May 29 20:54 public
-rw-r--r--  1 jfranks jfranks 5182 May 29 15:03 README.md
drwxr-xr-x  4 jfranks jfranks 4096 May 29 15:03 src
drwxr-xr-x  2 jfranks jfranks 4096 May 29 15:03 __tests__
-rw-r--r--  1 jfranks jfranks 1390 May 29 15:03 webpack.config.js
-rw-r--r--  1 jfranks jfranks 1822 May 29 20:50 webpack.production.config.js

**Comment by iroy2000** [comment]
Thanks again, the dummy unit test has a old file path which is not existed anymore, I just fixed the path.
