### ISSUE TITLE
'gulp test' seg fault

### ISSUE THREAD

**Issue by jefffranks** [iroy2000/react-reflux-boilerplate-with-webpack#4]
Hi,

Did an update 'git pull' and went through the work flow commands.

'gulp test' seg faults as follows:

---- console session ----
jfranks@jlf-mint-17 ~/Desktop/ws3 - react reflux boilerplate with webpack/react-reflux-boilerplate-with-webpack $ gulp test
[14:03:44] Requiring external module coffee-script/register
[14:03:47] Using gulpfile ~/Desktop/ws3 - react reflux boilerplate with webpack/react-reflux-boilerplate-with-webpack/gulpfile.coffee
[14:03:47] Starting 'test'...
Waiting on 1 test...Segmentation fault
---- end of console session ----

**Comment by iroy2000** [comment]
Let me look into that later, probably not today,
never had that issue before.  I will give an update here.

**Comment by iroy2000** [comment]
I just give it a try, it doesn't happen to me though.

What is your node version ?  And what is your Jest version ?

You might want to look at the following github issues from Jest, which is similar to yours

https://github.com/facebook/jest/issues/266

https://github.com/facebook/jest/issues/271

**Comment by jefffranks** [comment]
My node version is v0.12.2

How do I obtain the jest version?

**Comment by jefffranks** [comment]
I just did an install of jest-cli @ 0.2.2
npm is 2.8.3

I re-ran 'gulp test' w/ same seg-fault result.

What do I have to do to avoid this result?

**Comment by iroy2000** [comment]
Did you look into the link I quote in the above comment ??

If you look into the issue link I put in above comment, it is a known issue that Jest doesn't support React in `NodeJS v0.12.x`

My node version is the following, and it works well

```sh
node --version
v0.10.33
```

Two things you can do
1) Bump down your node version to not using 0.12.x
2) Continue to communicate with Jest community and see if there is any update on that issue
