### ISSUE TITLE
'gulp test' FAIL

### ISSUE THREAD

**Issue by jefffranks** [iroy2000/react-reflux-boilerplate-with-webpack#5]
Well, I've changed node version to v0.10.33 as suggested -- no more seg faults.
Started over with the command flow . . .
But 'gulp test' has a FAIL shown from the console session:

-------------- console session  -------------------
Dropping unused variable object [./~/lodash/index.js:948,10]
Condition always true [./~/lodash/index.js:12207,6]
Dropping unreachable code [./~/lodash/index.js:12221,7]
Side effects in initialization of unused variable moduleExports [./~/lodash/index.js:275,6]
[16:12:28] Finished 'webpack:build' after 43 s
[16:12:28] Starting 'build'...
[16:12:28] Finished 'build' after 12 μs
jfranks@jlf-mint-17 ~/Desktop/ws3 - react reflux boilerplate with webpack/react-reflux-boilerplate-with-webpack $ gulp test
[16:12:35] Requiring external module coffee-script/register
[16:12:37] Using gulpfile ~/Desktop/ws3 - react reflux boilerplate with webpack/react-reflux-boilerplate-with-webpack/gulpfile.coffee
[16:12:37] Starting 'test'...
 FAIL  __tests__/app.cjsx
Error: /home/jfranks/Desktop/ws3 - react reflux boilerplate with webpack/react-reflux-boilerplate-with-webpack/node_modules/jest-cli/node_modules/jsdom/node_modules/contextify/build/Release/contextify.node: undefined symbol: node_module_register
1 test failed, 0 tests passed (1 total)
Run time: 0.241s
[16:12:42] Finished 'test' after 4.93 s
----------------------------------

**Comment by iroy2000** [comment]
Maybe it is because after you downgrade your Node,  but the dependencies you have for your project are based on your previous Node version.   What I would suggest is check out a brand new boilerplate repo, and go through the setup again.  Let me know how that goes.

**Comment by wubenhe** [comment]
after you have downgrade the nodejs, you have to remove your local .npm folder in your home folder, and your node_modules folder as well. Because the react framework need recompile, so you need to remove all the cache. 
```
rm ~/.npm 
npm install 
npm test
```

**Comment by jefffranks** [comment]
Yes, this issue is resolved.
Applying your suggestions fixed the issue I was having.
I'm now using node v0.10.33 and npm v2.11.1 after having removed all areas of cache, libs, etc.
Thank you very much for your help.

======= console session showing 'gulp test' that passed =============
jfranks@jlf-mint-17 ~/Desktop/ws3 - React Reflux Boilerplate With Webpack/react-reflux-boilerplate-with-webpack $ gulp test
[15:03:19] Requiring external module coffee-script/register
[15:03:22] Using gulpfile ~/Desktop/ws3 - React Reflux Boilerplate With Webpack/react-reflux-boilerplate-with-webpack/gulpfile.coffee
[15:03:22] Starting 'test'...
 PASS  __tests__/app.cjsx (1.738s)
1 test passed (1 total)
Run time: 2.044s
[15:04:02] Finished 'test' after 40 s

**Comment by iroy2000** [comment]
Thanks, closing the ticket now :)
