### ISSUE TITLE
Webpack css hot reload not work when stylus @import other stylus file.

### ISSUE THREAD

**Issue by milescui** [iroy2000/react-reflux-boilerplate-with-webpack#6]
Hi,

Webpack-dev-server css hot reload not work when stylus @import other stylus file.

Thanks

**Comment by iroy2000** [comment]
Hi @milescui ,

Just come back from my vacation, thanks for your questions :)

In Webpack, the query parameter `importLoaders` allows to configure which loaders should be applied to @imported resources.

You may want to try the following:

After your css loader in webpack, maybe you can try to add `?importLoaders=1`

I will try to reproduce that tonight as well and applied the fixes if applicable.  Feel free to send pull request if you find the right solution as well.

Thanks

**Comment by milescui** [comment]
Hi @iroy2000 

Thanks for your answer :)

?importLoaders=1 not work for me

I found a similar problem: [https://github.com/shama/stylus-loader/issues/45](https://github.com/shama/stylus-loader/issues/45)

I have a not perfect solution. I found that if webpack css HMR not work, webpack HMR can be triggered by way of saving public/main.css files. So, I modified the gulpfile.coffee, save 'public/main.css' in each gulp css task.

``` coffeescript
# CSS
gulp.task('css', ->
  gulp.src(['src/styles/*.styl'])
    .pipe(stylus({
        use: [nib(), jeet(), rupture()]
        compress: true 
    }))
    .on('error', (err) ->
      gutil.log err
      @emit('end')
    )
    .pipe($.size())
    .pipe(gulp.dest(paths.dest))
    .pipe(shell([  # here is my modified code
      'sleep 2; echo <%= file.path %>',
      'touch <%= file.path %>'
    ]))
    .pipe(map((a, cb) ->
      if devServer.invalidate? then devServer.invalidate()
      cb()
    ))
)
```

Thanks

**Comment by iroy2000** [comment]
@milescui  Thanks for your answer.

I will look into that later, glad your solution works out.

I will keep this post open for now until the problem is solved.   And hope this will help out other people.

**Comment by MikaelStenstrand** [comment]
I have the same problem. What is the solution for this?

**Comment by iroy2000** [comment]
I'm trying to look into that today and I'm able to reproduce this issue, I will need to look into that deeper :)

As of right now,  here is the link I found related to issues for react-hot-loader, I will look into that as well

https://github.com/gaearon/react-hot-loader/blob/master/docs/Troubleshooting.md

So far there is a solution that mentioned by @milescui above.

**Comment by iroy2000** [comment]
Using @milescui solution to fix the issue.  Please feel free to issue pull request if you have better solution :)
