### ISSUE TITLE
shell is not defined

### ISSUE THREAD

**Issue by Aslan11** [iroy2000/react-reflux-boilerplate-with-webpack#7]
Hey Roy,

Thanks for putting this together man, really appreciate it. 

Just wanted to let you know that you forgot to require `gulp-shell` in the gulpfile so it's throwing an shell is undefined error. 

Best,

Kevin

**Comment by iroy2000** [comment]
Thanks Kevin, 

I just added it back. 

https://github.com/iroy2000/react-reflux-boilerplate-with-webpack/commit/f9240a64a5eb87a40924e4407795c06d4d34a4e1
