### ISSUE TITLE
Stylus source maps

### ISSUE THREAD

**Issue by szhu** [iroy2000/react-reflux-boilerplate-with-webpack#8]
Looks like CSS source maps are emitted only in production mode. Any way to get CSS source maps for dev mode as well?

I spent a few hours looking into this but I'm not very familiar with the build tools so I wasn't able to figure it out.

**Comment by iroy2000** [comment]
In webpack, there is a config "devtool", and you can set it to "eval-cheap-module-source-map"

For example, in your development mode, you can add the following to your webpackConfig object

`webpackConfig.devtool   = 'eval-cheap-module-source-map';`
`webpackConfig.debug     = true;`

You can go to this link - http://webpack.github.io/docs/build-performance.html  and search for `SOURCEMAPS`.

**Comment by szhu** [comment]
Thank you! Is there a reason this is not enabled by default? It seems super helpful.

**Comment by iroy2000** [comment]
@szhu Sure, I definitely can put that in. Actually I used `'eval-cheap-module-source-map'` when I started my own projects, and seems like it is mostly the use case for others. 

Thanks
